services:
  estoque-api:
    build:
      context: ./estoque
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL_ESTOQUE}
    depends_on:
      - estoque-db
    networks:
      - backend

  estoque-db:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - estoque-db-data:/var/lib/postgresql/data
    networks:
      - backend

  faturamento-api:
    build:
      context: ./faturamento
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL_FATURAMENTO}
      - ESTOQUE_URL=${ESTOQUE_URL}
    depends_on:
      - faturamento-db
    networks:
      - backend

  faturamento-db:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - faturamento-db-data:/var/lib/postgresql/data
    networks:
      - backend

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend-node_modules:/app/node_modules
    ports:
      - '4200:4200'
    command: sh -c "npm install && npm start -- --host 0.0.0.0 --proxy-config proxy.conf.json"
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=${FRONTEND_CHOKIDAR_USEPOLLING}
    depends_on:
      - estoque-api
      - faturamento-api
    networks:
      - backend

volumes:
  estoque-db-data:
  faturamento-db-data:
  frontend-node_modules:

networks:
  backend:
